-- GENERATED by tools/render/pack.py from render/beached.toml. DO NOT EDIT.
--
-- Every number here was measured off the rendered frames: the frame box is the
-- union of all 72 animation frames' alpha, and the shift is the distance from the render
-- canvas's own origin pixel to the cropped frame's centre. The JSON manifest
-- beside the sheets is these same tables plus an id, which is what
-- tools/lint_sprites.py checks against the real PNGs.
--
-- SEQUENCE beached (C.21): 117 played frames at 24 fps out of 72 unique renders, one
-- direction (16). frame_sequence is the order they play in; a repeated cell is
-- loaded once. config_hash below is the digest over every frame's own config
-- hash, so it moves if any frame's knobs do. Every sheet carries its
-- animation_speed (0.4: 24 fps against the engine's 60 ticks a second).
--
-- config a5b3c3f1531c   packed 2026-09-26 14:34:45

local sprites = {}

sprites.body =
{
  filename = "__jamaltron__/graphics/jamaltron-beached-body.png",
  width = 283,
  height = 172,
  line_length = 8,
  frame_count = 72,
  frame_sequence = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
    51, 52, 53, 54, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 56,
    57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 20
  },
  animation_speed = 0.4,
  scale = 0.5,
  shift = {0.6015625, -0.375}
}

sprites.shadow =
{
  filename = "__jamaltron__/graphics/jamaltron-beached-body-shadow.png",
  width = 316,
  height = 121,
  line_length = 8,
  frame_count = 72,
  frame_sequence = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
    51, 52, 53, 54, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 56,
    57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 20
  },
  animation_speed = 0.4,
  scale = 0.5,
  shift = {1.15625, 0.0703125},
  draw_as_shadow = true
}

-- The slots as the entity prototype wants them. graphics_set[slot] = value,
-- which REPLACES the stock layer stack wholesale -- a layer we do not emit
-- cannot survive underneath.
local slots =
{
  animation = {layers = {sprites.body}},
  shadow_animation = sprites.shadow,
}

-- Stock graphics_set slots NO sheet of ours covers. entity.lua deepcopies the
-- spidertron, so these still hold WUBE'S art and must be set to nil, or a stock
-- plate draws under the shark. base_animation is deliberate, not missing: at the
-- C.13 harness ratio all 8 mounts land on the shark's own silhouette at all 64
-- rotations (512/512 samples measured), so there is nothing for a plate to cover.
local clear =
{
  "base_animation",
  "shadow_base_animation",
  "water_reflection",
}

return
{
  config_hash = "a5b3c3f1531c",
  sprites = sprites,
  slots = slots,
  clear = clear,
}
