-- GENERATED by tools/render/pack.py from render/jamaltron.toml. DO NOT EDIT.
--
-- Every number here was measured off the rendered frames: the frame box is the
-- union of all 64 rotations' alpha, and the shift is the distance from the render
-- canvas's own origin pixel to the cropped frame's centre. The JSON manifest
-- beside the sheets is these same tables plus an id, which is what
-- tools/lint_sprites.py checks against the real PNGs.
--
-- config 83d6be794998   packed 2026-09-20 16:04:57

local sprites = {}

sprites.body =
{
  filename = "__jamaltron__/graphics/jamaltron-body.png",
  width = 360,
  height = 289,
  line_length = 8,
  direction_count = 64,
  frame_count = 1,
  scale = 0.5,
  shift = {0, -0.4453125}
}

sprites.body_mask =
{
  filename = "__jamaltron__/graphics/jamaltron-body-mask.png",
  width = 166,
  height = 121,
  line_length = 8,
  direction_count = 64,
  frame_count = 1,
  scale = 0.5,
  shift = {0, 0.1640625},
  apply_runtime_tint = true
}

sprites.shadow =
{
  filename = "__jamaltron__/graphics/jamaltron-body-shadow.png",
  width = 405,
  height = 256,
  line_length = 8,
  direction_count = 64,
  frame_count = 1,
  scale = 0.5,
  shift = {0.6484375, 0},
  draw_as_shadow = true
}

sprites.reflection =
{
  filename = "__jamaltron__/graphics/jamaltron-body-water-reflection.png",
  width = 332,
  height = 192,
  line_length = 1,
  variation_count = 1,
  scale = 0.5,
  shift = {0, -0.09375}
}

-- The slots as the entity prototype wants them. graphics_set[slot] = value,
-- which REPLACES the stock layer stack wholesale -- a layer we do not emit
-- cannot survive underneath.
local slots =
{
  animation = {layers = {sprites.body, sprites.body_mask}},
  shadow_animation = sprites.shadow,
  water_reflection = {pictures = sprites.reflection},
}

-- Stock graphics_set slots NO sheet of ours covers. entity.lua deepcopies the
-- spidertron, so these still hold WUBE'S art and must be set to nil, or a stock
-- plate draws under the shark. base_animation is deliberate, not missing: at the
-- C.13 harness ratio all 8 mounts land on the shark's own silhouette at all 64
-- rotations (512/512 samples measured), so there is nothing for a plate to cover.
local clear =
{
  "base_animation",
  "shadow_base_animation",
}

return
{
  config_hash = "83d6be794998",
  sprites = sprites,
  slots = slots,
  clear = clear,
}
