"""B.5's generator: the catalog in, two files out, and every refusal it promises.

The load-bearing test is the first one. The generated files are COMMITTED, the catalog is
edited by hand, and a catalog edit that is not followed by a regenerate ships a mod whose
strings disagree with the file everyone reads -- so CI regenerates in memory and refuses a
stale commit. The rest pin the contract the catalog documents in its own header, each
refusal checked against a catalog built to trip exactly that one.
"""

import pathlib
import textwrap

import pytest

import gen_lines as g

HEADER = "| ID | Line | CH | SOURCE | BK | W | TIER | SUB | GATE | CHAIN | GRP | Note |"
RULE = "|---|---|---|---|---|---|---|---|---|---|---|---|"


def row(rid, line="Jamal is fine.", ch="speech", source="original", bk="-", w="3",
        tier="quiet", sub="-", gate="-", chain="-", grp=None, note="n"):
    return "| %s |" % " | ".join([rid, line, ch, source, bk, w, tier, sub, gate, chain,
                                  grp or rid, note])


def section(title, key, split, rows):
    return "\n".join(["## " + title, "", "**key:** " + key, "**split:** " + split,
                      "**fires:** whenever", "", HEADER, RULE] + rows + [""])


#: Header prose plus a table that is NOT a pool -- the real catalog has several, and the
#: parser has to walk past them.
PREAMBLE = "# Catalog\n\nprose, and a table:\n\n| a | b |\n|---|---|\n| 1 | 2 |\n\n"


def catalog(*sections):
    return PREAMBLE + "\n".join(sections)


#: Tests that run against the REAL catalog, where the real allow-lists must stay in force.
real_catalog = pytest.mark.real_catalog


@pytest.fixture(autouse=True)
def no_real_catalog_lists(request, monkeypatch):
    """The allow-repeat pair and the two ruled over-cap rows name REAL catalog rows, and
    validate() refuses a list naming a row that does not exist -- which is right for the
    real catalog and noise for a three-row one built to trip something else. So every test
    gets empty lists unless it is marked as running on the real catalog."""
    if request.node.get_closest_marker("real_catalog") is None:
        monkeypatch.setattr(g, "ALLOW_REPEAT", ())
        monkeypatch.setattr(g, "OVER_CAP_RULED", {})


def errors_of(text, extracts=None):
    with pytest.raises(g.CatalogError) as exc:
        g.build(text, extracts)
    return str(exc.value)


# ----------------------------------------------------------------------- the real catalog


@real_catalog
def test_the_committed_files_are_what_the_catalog_generates_today():
    """The staleness gate. Runs without the gitignored extracts, which is exactly CI.

    SKIPS until the generated files exist, and that is a DECISION, not a gap: running the
    generator into the repo is the B.5 id freeze, which character/REVIEW.md names as one of
    chotchki's one-way doors, sequenced after his D1-D10 calls. The generator is built and
    tested; the freeze is his to take. Exactly ONE file present is never a skip -- that is
    a half-committed generation, and it fails."""
    present = [p.exists() for p in (g.LUA_OUT, g.CFG_OUT)]
    if not any(present):
        pytest.skip("B.5 id freeze not taken yet (chotchki's call, character/REVIEW.md); "
                    "run gen_lines.py to take it")
    assert all(present), "only one generated file is committed: %s / %s" % (g.LUA_OUT.name,
                                                                        g.CFG_OUT.name)
    lua, cfg, _, notes = g.build(g.CATALOG.read_text(encoding="utf-8"), None)
    assert g.LUA_OUT.read_text(encoding="utf-8") == lua, "run: uv run --directory tools " \
        "python gen_lines.py"
    assert g.CFG_OUT.read_text(encoding="utf-8") == cfg, "run: uv run --directory tools " \
        "python gen_lines.py"
    assert any("NOT checked" in n for n in notes), "no extracts, so it must SAY it did not check"


@real_catalog
def test_the_real_catalog_meets_its_own_contract():
    sections = g.parse(g.CATALOG.read_text(encoding="utf-8"))
    assert g.validate(sections) == []
    ids = [r.id for s in sections for r in s.rows]
    assert len(ids) == len(set(ids))


@real_catalog
def test_the_generated_files_carry_the_header_and_fit_the_linter():
    lua, cfg, _, _ = g.build(g.CATALOG.read_text(encoding="utf-8"), None)
    assert lua.splitlines()[0].startswith("-- GENERATED by tools/gen_lines.py")
    assert cfg.splitlines()[0].startswith("# GENERATED by tools/gen_lines.py")
    assert max(len(line) for line in lua.splitlines()) <= g.LUA_WIDTH, ".luacheckrc is 120"


@real_catalog
def test_the_locale_file_is_not_the_hand_written_one():
    """jamaltron.cfg is hand-written and says the lines land in their own file; a generator
    writing into it would eat the entity names on its first run."""
    assert g.CFG_OUT.name == "jamaltron-lines.cfg"
    hand = (g.CFG_OUT.parent / "jamaltron.cfg").read_text(encoding="utf-8")
    assert "GENERATED" not in hand and "[jamaltron-line]" not in hand


# ----------------------------------------------------------------------------- emission


def test_a_required_split_whose_sides_are_the_keys_is_two_pools():
    text = catalog(section("enter/exit", "`enter` and `exit` — two pools",
                           "required — `enter` | `exit`. prose",
                           [row("enter.01", sub="enter"), row("exit.01", "Bye.", sub="exit")]))
    lua, _, _, _ = g.build(text, None)
    assert "    enter = {" in lua and "    exit = {" in lua
    assert 'sub = "enter"' not in lua, "inside its own pool the side is the pool, not a SUB"


def test_a_required_fork_keeps_one_pool_and_names_the_side():
    text = catalog(section("legs break", "`legs_break`", "required — `self` | `external`.",
                           [row("legs_break.01", sub="self"),
                            row("legs_break.02", "Not Jamal.", sub="external")]))
    lua, _, _, _ = g.build(text, None)
    assert 'sides = {"self", "external"}' in lua and 'sub = "external"' in lua
    assert "swap = true" in lua


def test_gated_dash_and_any_are_the_same_value_and_none_drops_sub():
    text = catalog(
        section("land", "`land`", "gated — `outcome`: `any` | `held` | `broke`. prose",
                [row("land.01", sub="-"), row("land.02", "Held!", sub="held")]),
        section("idle", "`idle`", "none — `SUB = sincere` is advisory",
                [row("idle.01", "Hm.", sub="sincere")]))
    lua, _, _, _ = g.build(text, None)
    assert 'id = "land.01", grp = "land.01", ch = "speech", w = 3, tier = "quiet", sub = "any"' \
        in lua
    assert 'values = {"held", "broke"}' in lua
    assert "sincere" not in lua, "an advisory SUB on a `none` split must not reach the picker"


def test_n_becomes_the_locale_parameter_and_the_row_asks_for_the_count():
    text = catalog(section("repaired", "`repaired`", "none",
                           [row("repaired.01", "Set {N} is fitted.")]))
    lua, cfg, _, _ = g.build(text, None)
    assert "repaired.01=Set __1__ is fitted." in cfg
    assert "count = true" in lua


def test_one_locale_key_per_id_even_for_a_reused_string():
    text = catalog(section("built", "`built`", "none",
                           [row("built.01", "Same."), row("built.02", "Same.", grp="built.01")]))
    _, cfg, _, _ = g.build(text, None)
    assert "built.01=Same." in cfg and "built.02=Same." in cfg


def test_a_chain_emits_the_computed_delay_and_the_tail_flag():
    head = "Jamal is quite excited to battle with his new upgrades"          # 54 characters
    text = catalog(section("built", "`built`", "none", [
        row("built.01", head, chain="built.02@180"),
        row("built.02", "It is a very robust excitement.", chain="tail-only")]))
    lua, _, _, _ = g.build(text, None)
    assert 'follow = "built.02", delay = 180' in lua and "tail_only = true" in lua


@pytest.mark.parametrize("length,ticks", [(54, 180), (36, 120), (44, 150), (32, 120),
                                          (50, 180), (41, 150), (33, 120), (15, 60), (5, 60)])
def test_chain_delay_is_the_catalogs_formula(length, ticks):
    """The nine shipped chains' own numbers, plus the floor."""
    assert g.chain_delay("x" * length) == ticks


# ----------------------------------------------------------------------------- refusals


def one(*rows, split="none", key="`built`", title="built"):
    return catalog(section(title, key, split, list(rows)))


@pytest.mark.parametrize("bad,expect", [
    (one(row("built.01", ch="whisper")), "CH 'whisper'"),
    (one(row("built.01", tier="loud")), "TIER 'loud'"),
    (one(row("built.01", gate="daily")), "GATE 'daily'"),
    (one(row("built.01", source="made up")), "SOURCE"),
    (one(row("built.01", source="verbatim", bk="-")), "want 7 or 8"),
    (one(row("built.01", w="0")), "not positive"),
    (one(row("idle.01")), "not <key>.<nn>"),
    (one(row("built.01"), row("built.01", "Other.")), "duplicate ID built.01"),
    (one(row("built.01", "Jamal can't.")), "ASCII apostrophe"),
    (one(row("built.01", "Hello {PLAYER}.")), "{PLAYER}"),
    (one(row("built.01", "x" * 61)), "over the 60 bubble cap"),
    (one(row("built.01", "Same."), row("built.02", "Same.")), "GRP 'built.02'"),
    (one(row("built.01", sub="left"), split="required — `self` | `external`."),
     "not a side"),
    (one(row("built.01", sub="lava"), split="gated — `reason`: `any` | `water`."),
     "not a reason value"),
    (one(row("built.01", chain="sideways")), "CHAIN 'sideways'"),
    (one(row("built.01", chain="built.09@60")), "does not exist"),
    (one(row("built.01", chain="built.02@60"), row("built.02", "Tail.")), "not tail"),
    (one(row("built.01", "Tail.", chain="tail")), "no head names it"),
    (one(row("built.01", chain="built.02@90"), row("built.02", "T.", chain="tail")),
     "not the formula's 60"),
    (one(row("repaired.01", chain="repaired.02@60"),
         row("repaired.02", "T.", chain="tail-only"), key="`repaired`", title="repaired"),
     "swap"),
])
def test_every_contract_breach_is_refused_by_name(bad, expect):
    assert expect in errors_of(bad)


def test_narration_is_not_held_to_the_bubble_cap():
    """The cap is a speech-BUBBLE constraint and narration renders outside one."""
    g.build(one(row("built.01", "x" * 70, ch="narration")), None)


def test_the_ruled_long_rows_may_stay_long_and_nothing_else_may(monkeypatch):
    monkeypatch.setattr(g, "ALLOW_REPEAT", ())
    monkeypatch.setattr(g, "OVER_CAP_RULED", {"flopping.38": 61})
    g.build(catalog(section("flopping", "`flopping`", "none", [row("flopping.38", "x" * 61)])),
            None)
    over = catalog(section("flopping", "`flopping`", "none",
                           [row("flopping.38", "x" * 61), row("flopping.39", "y" * 61)]))
    out = errors_of(over)
    assert "flopping.39 is 1 characters over" in out and "flopping.38 is" not in out


def test_a_ruled_list_naming_a_row_that_is_gone_is_refused(monkeypatch):
    """If a ruled row is ever cut, its allowance must not linger to cover a future row."""
    monkeypatch.setattr(g, "ALLOW_REPEAT", ())
    monkeypatch.setattr(g, "OVER_CAP_RULED", {"flopping.38": 61})
    assert "OVER_CAP_RULED names flopping.38" in errors_of(one(row("built.01")))


def test_a_chain_across_pools_is_refused():
    text = catalog(section("built", "`built`", "none", [row("built.01", chain="idle.01@60")]),
                   section("idle", "`idle`", "none", [row("idle.01", "T.", chain="tail")]))
    assert "another pool" in errors_of(text)


def test_every_problem_is_reported_at_once():
    """A generator that stops at the first problem turns one pass of fixes into ten."""
    text = one(row("built.01", ch="whisper"), row("built.02", "B.", tier="loud"))
    out = errors_of(text)
    assert "CH 'whisper'" in out and "TIER 'loud'" in out


def test_a_short_row_is_refused_with_its_line_number():
    text = one(row("built.01")).replace("| Jamal is fine. |", "|", 1)
    assert "11 cells, want 12" in errors_of(text)


def test_a_missing_split_line_is_refused():
    text = one(row("built.01")).replace("**split:** none\n", "")
    assert "no **split:** line" in errors_of(text)


def test_an_empty_note_is_allowed_and_an_empty_line_is_not():
    g.build(one(row("built.01", note="")), None)
    assert "empty Line" in errors_of(one(row("built.01", line="")))


# ----------------------------------------------------------------------------- fidelity


def extracts(tmp_path, book7="", book8=""):
    (tmp_path / "book7_jamal.txt").write_text(book7, encoding="utf-8")
    (tmp_path / "book8_jamal.txt").write_text(book8, encoding="utf-8")
    return tmp_path


def test_a_verbatim_line_not_in_its_book_is_a_fabrication(tmp_path):
    ex = extracts(tmp_path, book7="... Jamal is very excited about this, he said ...")
    ok = one(row("built.01", "Jamal is very excited about this", source="verbatim", bk="7"))
    _, _, _, notes = g.build(ok, ex)
    assert any("checked against the extracts" in n for n in notes)
    bad = one(row("built.01", "Jamal is very excited about that", source="verbatim", bk="7"))
    assert "fabrication" in errors_of(bad, ex)


def test_the_book_quote_behind_an_adapted_row_is_checked_too(tmp_path):
    ex = extracts(tmp_path, book8="Mister Carl, Jamal is sorry.")
    good = 'ORIGINAL: "Mister Carl, Jamal is sorry."'
    g.build(one(row("built.01", "Mr. Engineer, Jamal is sorry.", source="adapted", bk="8",
                    note=good)), ex)
    bad = 'ORIGINAL: "Mister Donut, Jamal is sorry."'
    assert "NOT in book 8" in errors_of(one(row("built.01", "Mr. Engineer, Jamal is sorry.",
                                                source="adapted", bk="8", note=bad)), ex)


def test_without_extracts_it_says_so_instead_of_passing_quietly(tmp_path):
    _, _, _, notes = g.build(one(row("built.01", source="verbatim", bk="7")), tmp_path)
    assert any("NOT checked" in n for n in notes)


@real_catalog
def test_check_mode_writes_nothing_and_fails_on_a_stale_file(tmp_path, monkeypatch, capsys):
    lua = tmp_path / "lines.lua"
    cfg = tmp_path / "lines.cfg"
    lua.write_text("stale", encoding="utf-8")
    monkeypatch.setattr(g, "LUA_OUT", lua)
    monkeypatch.setattr(g, "CFG_OUT", cfg)
    monkeypatch.setattr(g, "REPO", tmp_path)
    assert g.main(["--check", "--extracts", str(tmp_path / "none")]) == 1
    assert lua.read_text(encoding="utf-8") == "stale" and not cfg.exists()
    assert "STALE" in capsys.readouterr().out


@real_catalog
def test_the_catalog_header_names_the_file_the_generator_writes():
    """The catalog says which files are generated; it has to name the one that exists."""
    head = "\n".join(g.CATALOG.read_text(encoding="utf-8").splitlines()[:5])
    assert g.CFG_OUT.name in head, textwrap.shorten(head, 200)


# ------------------------------------------------ what the first review showed was untested


def test_every_emitted_field_reaches_the_lua():
    """Each field D.5 reads, emitted where the contract says. Mutation-checked: dropping any
    one of them used to leave this suite passing."""
    head = "Jamal is quite excited to battle with his new upgrades"
    text = catalog(
        section("land", "`land`", "gated — `outcome`: `any` | `held` | `broke`.",
                [row("land.01", sub="any", gate="once_per_save"),
                 row("land.02", head, chain="land.03@180"),
                 row("land.03", "Indeed.", chain="tail")]))
    lua, _, _, _ = g.build(text, None)
    for want in ('gate = "once_per_save"', "tail = true", 'dimension = "outcome"',
                 'event = "land"', 'tiers = {"quiet", "normal", "unbearable"}',
                 'locale_section = "jamaltron-line"', "swap = false"):
        assert want in lua, want


@real_catalog
def test_the_allow_repeat_pair_is_emitted_in_order():
    lua, _, _, _ = g.build(g.CATALOG.read_text(encoding="utf-8"), None)
    assert 'allow_repeat = {{"idle.01", "idle.02"}}' in lua


@pytest.mark.parametrize("bad,expect", [
    (one(row("built.01", source="original", bk="7")), "want -"),
    (one(row("enter.01", sub="exit"), row("exit.01", "Bye.", sub="exit"),
         key="`enter` and `exit` — two", split="required — `enter` | `exit`.",
         title="enter/exit"), "does not match its own pool"),
    (one(row("enter.01", sub="enter", chain="exit.01@60"),
         row("exit.01", "Bye.", sub="exit", chain="tail"),
         key="`enter` and `exit` — two", split="required — `enter` | `exit`.",
         title="enter/exit"), "another pool"),
    (one(row("died.01", chain="died.02@60"), row("died.02", "T.", chain="tail-only"),
         key="`died`", title="died"), "the death"),
    (one(row("built.01", "Jamal \\\\n jumps.")), "backslash"),
    (one(row("built.01", "Jamal __ITEM__x__ jumps.")), "backslash or `__`"),
    (one(row("built.01", "Mr. Engineer, Jamal is sorry.", source="adapted", bk="8",
             note="swapped the name")), "no ORIGINAL"),
    (one(row("built.01", "Jamal is here", source="verbatim", bk="7",
             note='TRIMMED (prefix) of "Jamal is gone, he said"')), "not inside the full quote"),
    (one(row("built.01", note='we could say "something"')), "reserves for book provenance"),
])
def test_the_checks_the_first_suite_let_through(bad, expect):
    assert expect in errors_of(bad)


def test_a_tail_may_have_more_than_one_head():
    """No source says a punchline belongs to one setup; the first draft invented the rule."""
    head = "Jamal is quite excited to battle with his new upgrades"
    g.build(one(row("built.01", head, chain="built.03@180"),
                row("built.02", head + "!", chain="built.03@180"),
                row("built.03", "It is robust.", chain="tail-only")), None)


@pytest.mark.parametrize("key", ["end", "Legs", "legs-break"])
def test_a_pool_key_that_is_not_a_lua_identifier_is_refused(key):
    text = catalog(section("x", "`%s`" % key, "none", [row("%s.01" % key.lower())]))
    assert "bare Lua identifier" in errors_of(text)


def test_two_sections_cannot_share_a_pool_key():
    text = catalog(section("built", "`built`", "none", [row("built.01")]),
                   section("built again", "`built`", "none", [row("built.02", "B.")]))
    assert "already the key of section" in errors_of(text)


def test_a_row_after_the_table_ended_is_refused_not_dropped():
    text = one(row("built.01")).replace(row("built.01"),
                                        row("built.01") + "\n\n" + row("built.02", "B."))
    assert "after the table ended" in errors_of(text)


def test_a_unicode_line_separator_in_a_cell_does_not_cut_the_row():
    lua, cfg, _, _ = g.build(one(row("built.01", "Jamal waves.")), None)
    assert "built.01=Jamal waves." in cfg


def test_shape_and_contract_problems_come_back_together():
    text = one(row("built.01", ch="whisper")) + "\n" + section(
        "idle", "`idle`", "none", ["| idle.01 | too | few |"])
    out = errors_of(text)
    assert "CH 'whisper'" in out and "3 cells, want 12" in out


@pytest.mark.parametrize("header,expect", [
    ("| ID | Line | CH |", "table header is"),
])
def test_a_wrong_header_is_refused(header, expect):
    assert expect in errors_of(one(row("built.01")).replace(HEADER, header))


def test_a_malformed_split_and_a_rowless_section_are_refused():
    assert "not none / required / gated" in errors_of(one(row("built.01"), split="required - `a`"))
    assert "has no rows" in errors_of(catalog(section("built", "`built`", "none", [])))


def test_a_pool_table_under_a_section_with_no_key_is_refused():
    text = PREAMBLE + "## loose\n\n" + HEADER + "\n" + RULE + "\n" + row("built.01") + "\n"
    assert "no **key:** line" in errors_of(text)


def test_a_ruled_long_row_is_exempt_only_up_to_its_ruled_length(monkeypatch):
    monkeypatch.setattr(g, "ALLOW_REPEAT", ())
    monkeypatch.setattr(g, "OVER_CAP_RULED", {"flopping.38": 61})
    g.build(catalog(section("flopping", "`flopping`", "none", [row("flopping.38", "x" * 61)])),
            None)
    out = errors_of(catalog(section("flopping", "`flopping`", "none",
                                    [row("flopping.38", "x" * 62)])))
    assert "longer than the 61 B.4 Q8 ruled on" in out


def test_the_allow_repeat_existence_check_bites(monkeypatch):
    monkeypatch.setattr(g, "ALLOW_REPEAT", (("built.01", "built.99"),))
    assert "names built.99" in errors_of(one(row("built.01")))


def test_a_quote_is_checked_against_its_own_book_only(tmp_path):
    ex = extracts(tmp_path, book7="nothing here", book8="Jamal is very excited about this,")
    bad = one(row("built.01", "Jamal is very excited about this", source="verbatim", bk="7"))
    assert "fabrication" in errors_of(bad, ex), "a book-8 string does not verify a book-7 row"


def test_a_trimmed_quote_is_verified_against_the_book(tmp_path):
    ex = extracts(tmp_path, book7="Jamal is very excited about this, he said.")
    bad = one(row("built.01", "Jamal is very", source="verbatim", bk="7",
                  note='TRIMMED (prefix) of "Jamal is very excited about THAT"'))
    assert "NOT in book 7" in errors_of(bad, ex)


def test_half_an_extracts_directory_is_an_error_not_a_crash(tmp_path):
    (tmp_path / "book7_jamal.txt").write_text("x", encoding="utf-8")
    assert "half-unpacked" in errors_of(one(row("built.01")), tmp_path)


def test_main_writes_both_files_and_exits_0_then_check_passes(tmp_path, monkeypatch, capsys):
    cat = tmp_path / "lines.md"
    cat.write_text(one(row("built.01")), encoding="utf-8")
    monkeypatch.setattr(g, "LUA_OUT", tmp_path / "out" / "lines.lua")
    monkeypatch.setattr(g, "CFG_OUT", tmp_path / "out" / "lines.cfg")
    monkeypatch.setattr(g, "REPO", tmp_path)
    args = ["--catalog", str(cat), "--extracts", str(tmp_path / "none")]
    assert g.main(args) == 0
    assert (tmp_path / "out" / "lines.cfg").read_text(encoding="utf-8").endswith(
        "built.01=Jamal is fine.\n")
    assert g.main(args + ["--check"]) == 0
    cat.write_text(one(row("built.01", ch="whisper")), encoding="utf-8")
    assert g.main(args) == 1 and "does not meet its own contract" in capsys.readouterr().err
