"""PLAN C.15's two leftover holes, closed as tests because CI runs this whole suite.

CI's sprite gate lints only manifests under STRICT_TREE and pack.py's generated Lua, so two
kinds of icon of ours could still ship unchecked:

  (a) one a HAND-WRITTEN prototype names (`icon = "__jamaltron__/..."` in item.lua) -
      no manifest, no generated banner, never a CI lint target;
  (b) a PNG nobody declares at all - a thumbnail.png dropped at the mod root, an icon
      copied into graphics/ ahead of the Lua that will use it.

Both checks take a mod root, so each runs on the real mod AND is proven to fail on a
planted bad case in a tmpdir. Since C.6 promoted the portrait (icons.py --promote) item.lua's
icon and tintable pair, technology.lua's tech icon and entity.lua's icon are all
`__jamaltron__`, and graphics/icons.json declares every icon PNG.

(a) has a sprite-shaped twin: a hand-written SPRITE table of ours (entity.lua's
minimap_representation pair, `size = {128, 128}`) is no CI lint target either, so every
`__jamaltron__` sprite declaration in non-generated Lua lints --strict here.

Stdlib + Pillow only, no Factorio: `__base__` paths are skipped, not resolved, because a
runner has no --factorio-data (the ci.yml sprite gate says the same).
"""

import json
import pathlib
import re
import textwrap

from PIL import Image

import lint_sprites
from lint_sprites import ModPaths
from test_lint_icons import _ci_declares_sprites, png

REPO = pathlib.Path(__file__).resolve().parents[2]
OURS = "__jamaltron__/"

#: ci.yml's own env, read out of the workflow - no copy of the two paths here.
_CI = (REPO / ".github" / "workflows" / "ci.yml").read_text()


def _ci_env(name: str) -> str:
    match = re.search(rf"^  {name}: (\S+)$", _CI, re.M)
    assert match, f"ci.yml's env {name} moved: re-point this test at it"
    return match.group(1)


MOD_ROOT = REPO / _ci_env("MOD_ROOT")
#: The strict tree RELATIVE to the mod root (graphics/), so a tmpdir mod can reuse it.
STRICT_TREE = pathlib.PurePosixPath(_ci_env("STRICT_TREE")).relative_to(_ci_env("MOD_ROOT"))

#: What an icon file is called: icons.py's candidate names (icon, icon-tintable[-mask],
#: technology, minimap[-selected], thumbnail) and base's own directories for them.
_ICON_STEM = re.compile(r"icon|thumbnail|technology|minimap", re.I)
_ICON_DIRS = {"icons", "technology"}


def _mods(mod_root: pathlib.Path) -> ModPaths:
    """ci.yml's `--mod-root jamaltron=$MOD_ROOT`, which wins over any manifest's roots."""
    mods = ModPaths()
    mods.add("jamaltron", mod_root)
    return mods


def _is_ours(spec: lint_sprites.IconSpec) -> bool:
    """A literal `__jamaltron__/` path, or an unresolved one that visibly builds one: the
    reader refuses to guess a concat, and a refusal about OUR file must fail, not vanish."""
    if spec.filename is not None:
        return spec.filename.startswith(OURS)
    return any(OURS in why for _, why in spec.bad_fields)


def our_lua_icons(mod_root: pathlib.Path) -> tuple[int, list[tuple[pathlib.Path, lint_sprites.IconSpec]]]:
    """(icon declarations seen, the ones that are ours) across every .lua under the mod.
    Control-stage `icon = M.ICON` is unresolved and not ours, so it drops out."""
    seen, ours = 0, []
    for path in sorted(mod_root.rglob("*.lua")):
        specs = lint_sprites.icon_specs_from_lua(path)
        seen += len(specs)
        ours += [(path, spec) for spec in specs if _is_ours(spec)]
    return seen, ours


def lua_icon_findings(mod_root: pathlib.Path) -> list[tuple[str, lint_sprites.Finding]]:
    """Gap (a): every icon of ours a Lua file names, checked --strict against the mod root.
    (file relative to the mod root, finding) pairs."""
    mods = _mods(mod_root)
    return [(path.relative_to(mod_root).as_posix(), finding)
            for path, spec in our_lua_icons(mod_root)[1]
            for finding in lint_sprites.check_icon(spec, mods, strict=True)]


#: pack.py's banner. Its modules are CI lint targets already (ci.yml's classifier).
_GENERATED = "GENERATED by tools/render/pack.py"


def lua_sprite_findings(mod_root: pathlib.Path) -> tuple[int, list[tuple[str, lint_sprites.Finding]]]:
    """(sprite declarations of ours seen, findings) across hand-written .lua under the mod,
    --strict. A declaration is ours when any of its filenames is `__jamaltron__/`, or when an
    unreadable filename visibly builds one."""
    mods = _mods(mod_root)
    seen, found = 0, []
    for path in sorted(mod_root.rglob("*.lua")):
        if _GENERATED in path.read_text(encoding="utf-8", errors="replace"):
            continue
        for spec in lint_sprites.specs_from_lua(path):
            if not (any(f.startswith(OURS) for f in spec.filenames)
                    or any(OURS in why for _, why in spec.bad_fields)):
                continue
            seen += 1
            found += [(path.relative_to(mod_root).as_posix(), finding)
                      for finding in lint_sprites.check_spec(spec, mods, strict=True)]
    return seen, found


def _rendered(found) -> list[str]:
    return [f"{rel}: {finding.render()}" for rel, finding in found]


def declared_icons(mod_root: pathlib.Path) -> dict[pathlib.Path, set[str]]:
    """{resolved file: kinds} for every icon of ours a gated place declares: a manifest
    ci.yml's classifier picks up under the strict tree (CI lints those), or a Lua icon
    field (lua_icon_findings lints those)."""
    mods = _mods(mod_root)
    declares_sprites = _ci_declares_sprites()
    out: dict[pathlib.Path, set[str]] = {}

    def add(filename: str | None, kind: str) -> None:
        if filename and filename.startswith(OURS):
            out.setdefault(mods.resolve(filename).resolve(), set()).add(kind)

    tree = mod_root / STRICT_TREE
    for manifest in sorted(tree.rglob("*.json")) if tree.is_dir() else []:
        if declares_sprites(str(manifest)):
            document = json.loads(manifest.read_text(encoding="utf-8"))
            for spec in lint_sprites.icon_specs_from_manifest(document, manifest):
                add(spec.filename, spec.kind)
    for _, spec in our_lua_icons(mod_root)[1]:
        add(spec.filename, spec.kind)
    return out


def icon_like(rel: pathlib.PurePath) -> bool:
    return bool(_ICON_DIRS & set(rel.parts[:-1])) or bool(_ICON_STEM.search(rel.stem))


def undeclared_icon_pngs(mod_root: pathlib.Path) -> list[str]:
    """Gap (b): icon-looking PNGs under the mod that no gated declaration names. The
    thumbnail must be declared AS a thumbnail; as a plain icon it skips the 144x144 and
    mod-root checks. On disk, not `git ls-files`: a CI checkout IS the tracked set, and
    locally a PNG should fail before it is committed."""
    declared = declared_icons(mod_root)
    out = []
    for path in sorted(mod_root.rglob("*")):
        if path.suffix.lower() != ".png" or not path.is_file():
            continue
        rel = path.relative_to(mod_root)
        kinds = declared.get(path.resolve(), set())
        if rel.as_posix() == "thumbnail.png":
            if "thumbnail" not in kinds:
                out.append(f"{rel.as_posix()} (not declared with kind 'thumbnail')")
        elif icon_like(rel) and not kinds:
            out.append(rel.as_posix())
    return out


# ------------------------------------------------------------------ the real mod

def test_ci_env_is_where_this_reads_it():
    assert MOD_ROOT.is_dir() and (MOD_ROOT / "info.json").is_file()
    assert (MOD_ROOT / STRICT_TREE).is_dir()


def test_every_lua_icon_of_ours_passes_strict():
    seen, ours = our_lua_icons(MOD_ROOT)
    # Not vacuous: item.lua's three, technology.lua's one, entity.lua's one (C.6).
    assert seen > 0, "the icon reader found nothing in the mod - the walk is broken"
    assert len(ours) >= 5, [spec.origin for _, spec in ours]
    found = lua_icon_findings(MOD_ROOT)
    assert found == [], _rendered(found)


def test_every_hand_written_lua_sprite_of_ours_passes_strict():
    seen, found = lua_sprite_findings(MOD_ROOT)
    # entity.lua's minimap pair at least.
    assert seen >= 2, "no hand-written sprite of ours found - the minimap pair moved?"
    assert found == [], _rendered(found)


def test_every_icon_png_in_the_mod_is_declared_where_a_gate_checks_it():
    assert undeclared_icon_pngs(MOD_ROOT) == []


# ------------------------------------------------------------------ planted: gap (a)

def _lua(mod_root: pathlib.Path, rel: str, src: str) -> None:
    path = mod_root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(textwrap.dedent(src))


def test_a_good_lua_icon_of_ours_passes(tmp_path):
    png(tmp_path, "graphics/icons/jamaltron.png", 120, 64)
    _lua(tmp_path, "prototypes/item.lua",
         'data:extend({{type = "item", name = "i", '
         'icon = "__jamaltron__/graphics/icons/jamaltron.png"}})')
    assert our_lua_icons(tmp_path)[0] == 1
    assert lua_icon_findings(tmp_path) == []


def test_a_bad_lua_icon_of_ours_fails(tmp_path):
    png(tmp_path, "graphics/icons/big.png", 240, 128)
    Image.new("RGB", (120, 64)).save(tmp_path / "graphics/icons/opaque.png")
    _lua(tmp_path, "prototypes/item.lua", """
        data:extend({
          {type = "item", name = "a", icon = "__jamaltron__/graphics/icons/big.png"},
          {type = "item", name = "b", icon = "__jamaltron__/graphics/icons/opaque.png"},
          {type = "item", name = "c", icon = "__jamaltron__/graphics/icons/gone.png"},
          {type = "item", name = "d", icon = "__jamaltron__/graphics/icons/" .. n .. ".png"},
        })
    """)
    found = lua_icon_findings(tmp_path)
    assert [(rel, f.code) for rel, f in found] == [
        ("prototypes/item.lua", "icon-size"),
        ("prototypes/item.lua", "icon-no-alpha"),
        ("prototypes/item.lua", "missing-file"),
        ("prototypes/item.lua", "unresolved-icon"),
    ], _rendered(found)


def test_stock_and_control_stage_icons_are_not_ours(tmp_path):
    # No --factorio-data on a runner, so `__base__` is out of scope, and a runtime
    # `icon = M.ICON` (breakage.lua's alert) is not a file at all.
    _lua(tmp_path, "prototypes/gun.lua",
         'data:extend({{type = "gun", name = "g", '
         'icon = "__base__/graphics/icons/flamethrower.png"}})')
    _lua(tmp_path, "scripts/alert.lua", "force.add_custom_alert{entity = e, icon = M.ICON}")
    seen, ours = our_lua_icons(tmp_path)
    assert (seen, ours) == (2, [])
    assert lua_icon_findings(tmp_path) == []


def test_a_bad_hand_written_lua_sprite_of_ours_fails(tmp_path):
    png(tmp_path, "graphics/map.png", 128, 128)
    _lua(tmp_path, "prototypes/entity.lua", """
        body.minimap_representation =
          {filename = "__jamaltron__/graphics/map.png", flags = {"icon"}, size = {128, 128}}
        body.selected_minimap_representation =
          {filename = "__jamaltron__/graphics/map.png", size = {256, 256}}
        body.other = {filename = "__jamaltron__/graphics/gone.png", size = {128, 128}}
        body.stock = {filename = "__base__/graphics/whatever.png", size = {1, 1}}
    """)
    # A generated module is CI's, not this test's, even when it is broken.
    _lua(tmp_path, "prototypes/sprites_generated.lua", f"""
        -- {_GENERATED}
        return {{filename = "__jamaltron__/graphics/gone.png", size = 64}}
    """)
    seen, found = lua_sprite_findings(tmp_path)
    assert seen == 3
    assert [(rel, f.code) for rel, f in found] == [
        ("prototypes/entity.lua", "sheet-too-small"),
        ("prototypes/entity.lua", "missing-file"),
    ], _rendered(found)


# ------------------------------------------------------------------ planted: gap (b)

def _manifest(mod_root: pathlib.Path, rel: str, icons: list) -> None:
    path = mod_root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({"version": 1, "mod_roots": {"jamaltron": ".."},
                                "sprites": [], "icons": icons}))


def test_undeclared_icon_pngs_are_found(tmp_path):
    png(tmp_path, "thumbnail.png", 144, 144)
    png(tmp_path, "graphics/icons/jamaltron.png", 120, 64)
    png(tmp_path, "graphics/jamaltron-technology.png", 480, 256)
    png(tmp_path, "graphics/minimap.png", 128, 128)
    png(tmp_path, "graphics/jamaltron-body.png", 64, 64)  # a sprite sheet, not an icon
    assert undeclared_icon_pngs(tmp_path) == [
        "graphics/icons/jamaltron.png",
        "graphics/jamaltron-technology.png",
        "graphics/minimap.png",
        "thumbnail.png (not declared with kind 'thumbnail')",
    ]


def test_declaring_them_where_a_gate_looks_clears_them(tmp_path):
    for name, size in (("thumbnail.png", (144, 144)), ("graphics/icons/jamaltron.png", (120, 64)),
                       ("graphics/jamaltron-technology.png", (480, 256))):
        png(tmp_path, name, *size)
    _manifest(tmp_path, f"{STRICT_TREE}/icons.json", [
        {"id": "thumb", "kind": "thumbnail", "filename": "__jamaltron__/thumbnail.png"},
        {"id": "tech", "kind": "technology",
         "filename": "__jamaltron__/graphics/jamaltron-technology.png"},
    ])
    _lua(tmp_path, "prototypes/item.lua",
         'data:extend({{type = "item", name = "i", '
         'icon = "__jamaltron__/graphics/icons/jamaltron.png"}})')
    assert undeclared_icon_pngs(tmp_path) == []


def test_a_declaration_no_gate_reads_does_not_count(tmp_path):
    png(tmp_path, "thumbnail.png", 144, 144)
    png(tmp_path, "graphics/icons/jamaltron.png", 120, 64)
    # Outside the strict tree CI never lints it (the stray tripwire refuses it outright);
    # without `sprites` ci.yml's classifier does not see it; a thumbnail declared as a
    # plain icon skips the thumbnail checks.
    _manifest(tmp_path, "icons.json",
              [{"id": "i", "filename": "__jamaltron__/graphics/icons/jamaltron.png"}])
    bare = tmp_path / STRICT_TREE / "bare.json"
    bare.write_text(json.dumps({"icons": [
        {"id": "i", "filename": "__jamaltron__/graphics/icons/jamaltron.png"}]}))
    _manifest(tmp_path, f"{STRICT_TREE}/icons.json", [
        {"id": "t", "kind": "icon", "icon_size": 144, "mipmaps": 1,
         "filename": "__jamaltron__/thumbnail.png"}])
    assert undeclared_icon_pngs(tmp_path) == [
        "graphics/icons/jamaltron.png",
        "thumbnail.png (not declared with kind 'thumbnail')",
    ]
